# Generated by Django 3.2 on 2023-09-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20230906_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='allergen_id',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photoquery',
            name='image',
            field=models.ImageField(upload_to='query'),
        ),
    ]
