# Generated by Django 3.2 on 2023-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20230907_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_dangerous',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
