# Generated by Django 3.2 on 2023-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_is_dangerous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='allergen_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
